function c = make_colors(n)
hsv= [  1, .5,  0;...
        1,  1,  0;...
       .5,  1,  0;...
        0,  1,  0;...
        0,  1, .5;...
        0,  1,  1;...
        0, .5,  1;...
        0,  0,  1;...
       .5,  0,  1;...
        1,  0,  1;...a
        1,  0, .5;...
        1,  0,  0;...
        ];
x  = [1:12]';
xq = linspace(1,12,n)';
hsv = [interp1(x,hsv(:,1),xq), interp1(x,hsv(:,2),xq), interp1(x,hsv(:,3),xq)];


interval = ceil(2*(n+1)/3); %traverse the circle in thirds to have maximally distance color pairs
idx = mod(((1:n)-1)*interval,n)+1;

c = hsv(idx,:);
% figure(6);clf;hold on
% for i = 1:length(c)
%     scatter(i,1,100,c(i,:),'filled')
% end